# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(help_text=b'Some details about the user.', max_length=500, null=True)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], help_text=b'Specify gender.', max_length=10, null=True)),
                ('photo', models.ImageField(help_text=b'Profile picture.', null=True, upload_to=b'')),
                ('date_of_birth', models.DateField(help_text=b'Date of birth.', null=True)),
                ('mobile_number', models.CharField(help_text=b'Verified mobile number with country code', max_length=15, null=True)),
                ('address', models.CharField(help_text=b'Local address of user.', max_length=250, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
