# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='planet',
            field=models.CharField(default=b'earth', max_length=100),
        ),
    ]
