# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-24 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsrequestsrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name=b'Record Date'),
        ),
    ]
