# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRequestsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_status', models.CharField(max_length=10)),
                ('request_type', models.CharField(max_length=10)),
            ],
        ),
    ]
